spring:
    profiles:
        # active: local
        active: dev
        # active: prod
        # active: ${activeProfile}
---
spring:
    config:
        activate:
            on-profile: local


---
spring:
    config:
        activate:
            on-profile: dev

---
spring:
    config:
        activate:
            on-profile: prod
