spring:
    profiles:
        # active: local
        active: dev
        # active: prod
        # active: ${activeProfile}
---
server:
    port: 80

spring:
    config:
        activate:
            on-profile: local


---
server:
    port: 80

spring:
    config:
        activate:
            on-profile: dev

---
server:
    port: 80

spring:
    config:
        activate:
            on-profile: prod
